# Generated by Django 4.2.7 on 2023-11-25 06:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import profiles.models
import profiles.validators


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "category",
                    models.IntegerField(
                        choices=[
                            (0, "Languages"),
                            (1, "Science"),
                            (2, "Maths"),
                            (3, "Arts and humanities"),
                            (4, "Social sciences"),
                        ]
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="historicalprofile",
            name="profile_pic",
            field=models.TextField(
                default="C:\\Users\\macli\\Documents\\Rzeczy\\WebDev\\Python\\TutoringApp\\tutoring-app\\tutoringApp\\media\\default_profile_pic.jpg",
                max_length=100,
                validators=[profiles.validators.FileSizeValidator],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_pic",
            field=models.ImageField(
                default="C:\\Users\\macli\\Documents\\Rzeczy\\WebDev\\Python\\TutoringApp\\tutoring-app\\tutoringApp\\media\\default_profile_pic.jpg",
                upload_to=profiles.models.profile_pic_directory_path,
                validators=[profiles.validators.FileSizeValidator],
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="level",
            field=models.IntegerField(
                choices=[
                    (0, "Elementary School"),
                    (1, "Middle School"),
                    (2, "High School"),
                    (3, "College"),
                    (4, "University"),
                ],
                default=0,
            ),
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number_of_hours",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                            profiles.validators.SessionLengthValidator,
                        ],
                    ),
                ),
                ("price_per_hour", models.PositiveIntegerField()),
                (
                    "session_length",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Duration of one tutoring session in minutes",
                        validators=[
                            django.core.validators.MinValueValidator(30),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=True,
                        help_text="Indicate if its a default, 1 session service that is created when adding the subject when the profile is created.",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.subject",
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.service",
                    ),
                ),
            ],
        ),
    ]
