# Generated by Django 4.2.7 on 2024-01-03 08:16

import django.utils.timezone
from django.db import migrations, models

import lessons.models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="subject",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="subject_details",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="title",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="material",
            name="file",
            field=models.FileField(
                max_length=250, upload_to=lessons.models.material_file_path
            ),
        ),
    ]
