# Generated by Django 4.2.7 on 2024-01-06 11:31

from django.db import migrations, models

import lessons.models
import lessons.validators


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0002_alter_lesson_date_alter_lesson_subject_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="file",
            field=models.FileField(
                max_length=250,
                upload_to=lessons.models.material_file_path,
                validators=[lessons.validators.MaterialFileExtensionValidator],
            ),
        ),
    ]
