# Generated by Django 4.2.7 on 2024-01-08 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lessons", "0003_alter_material_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solution",
            name="task",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="lessons.task"
            ),
        ),
    ]
